import { nanoid } from "nanoid";

const imagesJSON = [
  {
    key: nanoid(),
    id: 1,
    name: "Mark Webber",
    img: require("./pic1.png"),
    alt: "photo of Mark Webber",
    isRead: false,
    react: true,
    follow: false,
    comment: "",
    joined: false,
    left: false,
    msg: "",
  },
  {
    key: nanoid(),
    id: 2,
    name: "Angela Gray",
    img: require("./pic2.png"),
    alt: "photo of Angela Gray",
    isRead: false,
    react: false,
    follow: true,
    comment: "",
    joined: false,
    left: false,
    msg: "",
  },
  {
    key: nanoid(),
    id: 3,
    name: "Jacob Thompson",
    img: require("./pic5.png"),
    alt: "photo of Jacob Thompson",
    isRead: false,
    react: false,
    follow: false,
    comment: "",
    joined: true,
    left: false,
    msg: "",
  },
  {
    key: nanoid(),
    id: 4,
    name: "Rizky Hasanuddin",
    img: require("./pic4.png"),
    alt: "photo of Rizky Hasanuddin",
    isRead: false,
    react: false,
    follow: false,
    comment: "",
    joined: false,
    left: false,
    msg:
      "Hello, thanks for setting up the Chess Club.  I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
  },
  {
    key: nanoid(),
    id: 5,
    name: "Kimberly Smith",
    img: require("./pic3.png"),
    alt: "photo of Kimberly Smith",
    isRead: false,
    react: false,
    follow: false,
    comment: "Love this!",
    joined: false,
    left: false,
    msg: "",
  },
  {
    key: nanoid(),
    id: 6,
    name: "Nathan Peterson",
    img: require("./pic6.png"),
    alt: "photo of Nathan Peterson",
    isRead: false,
    react: true,
    follow: false,
    comment: "",
    joined: false,
    left: false,
    msg: "",
  },
  {
    key: nanoid(),
    id: 7,
    name: "Anna Kim",
    img: require("./pic7.png"),
    alt: "photo of Anna Kim",
    isRead: false,
    react: false,
    follow: false,
    comment: "",
    joined: false,
    left: true,
    msg: "",
  },
];

export { imagesJSON };
